---

dist: jammy

language: python

python:
  - "3.10.5"

services:
  - docker

env:
  - ANSIBLE_INVENTORY_UNPARSED_WARNING=False ANSIBLE_LOCALHOST_WARNING=False

script:
  # YAML check
  - yamllint tests/kpa_generator.yml
  # Ansible Linter check
  - ansible-lint tests/kpa_generator.yml
  # Ansible syntax check
  - ansible-playbook tests/kpa_generator.yml
    --syntax-check
  # Ansible effective execution (should produce a ./tests/slide.md)
  - ansible-playbook tests/kpa_generator.yml

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
