---

- name: Create Marp slides markdown
  ansible.builtin.template:
    src: slides.md.j2
    dest: "{{ marp_output_markdown }}"
    mode: '0640'

- name: Create Pandoc agenda markdown
  ansible.builtin.template:
    src: agenda.md.j2
    dest: "{{ pandoc_agenda_output_markdown }}"
    mode: '0640'

- name: Generate pdf slides with Marp
  shell: |
    marp --pdf \
      --allow-local-files \
      --html \
      --theme {{ marp_theme_path }} \
      -o {{ marp_output_pdf }} \
      {{ marp_output_markdown }}
  when:
    - marp_output_pdf is defined

- name: Generate pdf agenda with Pandoc
  shell: |
    pandoc --template={{ pandoc_agenda_template_file }} \
      {{ pandoc_agenda_output_markdown }} \
      -o {{ pandoc_agenda_output_pdf }}
  when:
    - pandoc_agenda_output_pdf is defined
