---

- name: Create Marp slides markdown
  ansible.builtin.template:
    src: slides.md.j2
    dest: "{{ marp_output_markdown }}"
    mode: '0640'

- name: Create Pandoc agenda markdown
  ansible.builtin.template:
    src: agenda.md.j2
    dest: "{{ pandoc_agenda_output_markdown }}"
    mode: '0640'

- name: Create Pandoc slides book markdown
  ansible.builtin.template:
    src: book.md.j2
    dest: "{{ pandoc_book_output_markdown }}"
    mode: '0640'

- name: Generate pdf slides with Marp
  ansible.builtin.shell: |
    marp --pdf \
      --allow-local-files \
      --html \
      {% if marp_theme_file is defined %}--theme {{ marp_theme_file }}{% endif %} \
      -o {{ marp_output_pdf }} \
      {{ marp_output_markdown }}
  when:
    - marp_output_pdf is defined
  register: marp_pdf_cmd
  changed_when: marp_pdf_cmd.rc == 0

- name: Generate pptx slides with Marp
  ansible.builtin.shell: |
    marp --pptx \
      --allow-local-files \
      --html \
      {% if marp_theme_file is defined %}--theme {{ marp_theme_file }}{% endif %} \
      -o {{ marp_output_pptx }} \
      {{ marp_output_markdown }}
  when:
    - marp_output_pptx is defined
  register: marp_pptx_cmd
  changed_when: marp_pptx_cmd.rc == 0

- name: Generate pdf agenda with Pandoc
  ansible.builtin.shell: |
    pandoc \
      {% if pandoc_agenda_template_file is defined %}--template={{ pandoc_agenda_template_file }}{% endif %} \
      {{ pandoc_agenda_output_markdown }} \
      -o {{ pandoc_agenda_output_pdf }}
  when:
    - pandoc_agenda_output_pdf is defined
  register: pandoc_agenda_cmd
  changed_when: pandoc_agenda_cmd.rc == 0

- name: Generate pdf book with Pandoc
  ansible.builtin.shell: |
    pandoc \
      {% if pandoc_book_template_file is defined %}--template={{ pandoc_book_template_file }}{% endif %} \
      {{ pandoc_book_output_markdown }} \
      -o {{ pandoc_book_output_pdf }}
  when:
    - pandoc_book_output_pdf is defined
  register: pandoc_book_cmd
  changed_when: pandoc_book_cmd.rc == 0
