---

name: Linter and test the project                                                        
                                                                                
env:
  ANSIBLE_INVENTORY_UNPARSED_WARNING: 'False'
  ANSIBLE_LOCALHOST_WARNING: 'False'

on: [push]  

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: quay.io/mmul/kpa
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: YAML check
        run: yamllint tests/kpa_marp_slides_generator.yml
      - name: Ansible Linter check
        run: ansible-lint tests/kpa_marp_slides_generator.yml
      - name: Ansible syntax check
        run: ansible-playbook --syntax-check tests/kpa_marp_slides_generator.yml

  test:
    runs-on: ubuntu-latest
    needs: lint
    container:
      image: quay.io/mmul/kpa
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Ansible execution preparation (remove tests/*.md)
        run: rm -f tests/*.md
      - name: Ansible execution (should produce the two .md files)
        run: ansible-playbook tests/kpa_marp_slides_generator.yml
      - name: Check tests/slides.md file existence
        run: test -f tests/slides.md
      - name: Check tests/slides.schedule.md file existence
        run: test -f tests/slides.schedule.md
