---

name: Linter and test, trigger Ansible Galaxy and KPA GitHub Actions

env:
  ANSIBLE_INVENTORY_UNPARSED_WARNING: 'False'
  ANSIBLE_LOCALHOST_WARNING: 'False'

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/mmul-it/kpa
      options: --user root
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: YAML check
        run: yamllint tests/kpa_generator.yml
      - name: Ansible Linter check
        run: ansible-lint tests/kpa_generator.yml
      - name: Ansible syntax check
        run: ansible-playbook --syntax-check tests/kpa_generator.yml

  test:
    runs-on: ubuntu-latest
    needs: lint
    container:
      image: ghcr.io/mmul-it/kpa
      options: --user root
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Ansible execution preparation (remove tests/*.md)
        run: rm -f tests/*.md
      - name: Ansible execution (should produce the two .md files)
        run: ansible-playbook tests/kpa_generator.yml
      - name: Check tests/slides.md file existence
        run: test -f tests/slides.md
      - name: Check tests/slides.pdf file existence
        run: test -f tests/slides.pdf
      - name: Check tests/slides.agenda.md file existence
        run: test -f tests/slides.agenda.md
      - name: Check tests/slides.agenda.pdf file existence
        run: test -f tests/slides.agenda.pdf

  trigger_galaxy_import:
    runs-on: ubuntu-latest
    needs: test
    container:
      image: ghcr.io/mmul-it/kpa
      options: --user root
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Trigger Ansible Galaxy to import the role
        run: ansible-galaxy role import --token ${{ secrets.GALAXY_API_KEY }} ${{ github.repository_owner }} ${{ github.event.repository.name }}

  trigger_kpa_rebuild:
    runs-on: ubuntu-latest
    needs: trigger_galaxy_import
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Trigger GitHub Actions workflow to rebuild KPA
        run: |
          curl \
          --request POST \
          --header 'Accept: application/vnd.github.v3+json' \
          --header "Authorization: Bearer ${{ secrets.ACTIONS_KEY }}" \
          --data '{"ref": "main"}' \
          https://api.github.com/repos/mmul-it/kpa/actions/workflows/main.yml/dispatches
